
# Server Configuration
server:
  port: 8080

# H2 Database Configuration
spring:
  main:
    banner-mode: off
  application:
    name: rewards-service
  datasource:
    url: jdbc:h2:mem:rewardsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: caffeine
    cache-names: rewards

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.program.rewards: DEBUG
    org.springframework.cache: DEBUG



rewards:
  cache:
    clear-cache-fixed-rate: 360000  # Cache clear interval in milliseconds (default: 10 minutes)